export const DATA = {
  SET_SCREAMS_START: "SET_SCREAMS_START",
  SET_SCREAMS_SUCCESS: "SET_SCREAMS_SUCCESS",
  LOADING_DATA: "LOADING_DATA",
  LIKE_SCREAM_START: "LIKE_SCREAM_START",
  LIKE_SCREAM_SUCCESS: "LIKE_SCREAM_SUCCESS",
  UNLIKE_SCREAM_START: "UNLIKE_SCREAM_START",
  UNLIKE_SCREAM_SUCCESS: "UNLIKE_SCREAM_SUCCESS",
  DELETE_SCREAM_START: "DELETE_SCREAM_START",
  DELETE_SCREAM_SUCCESS: "DELETE_SCREAM_SUCCESS",
  POST_SCREAM_START: "POST_SCREAM_START",
  POST_SCREAM_SUCCESS: "POST_SCREAM_SUCCESS",
  GET_SCREAM_START: "GET_SCREAM_START",
  GET_SCREAM_SUCCESS: "GET_SCREAM_SUCCESS"
};
