export const USER = {
  SET_AUTHENTICATED: "SET_AUTHENTICATED",
  SET_UNAUTHENTICATED: "SET_UNAUTHENTICATED",
  SIGNUP_START: "SIGNUP_START",
  LOGIN_WITH_EMAIL_AND_PASSWORD_START: "LOGIN_WITH_EMAIL_AND_PASSWORD_START",
  LOGOUT_START: "LOGOUT_START",
  LOADING_USER: "LOADING_USER",
  CHECK_USER_START: "CHECK_USER_START",
  UPLOAD_USER_IMAGE_START: "UPLOAD_USER_IMAGE_START",
  UPDATE_USER_DETAILS_START: "UPDATE_USER_DETAILS_START",
  MARK_NOTIFICATIONS_READ_START: "MARK_NOTIFICATIONS_READ_START",
  MARK_NOTIFICATIONS_READ_SUCCESS: "MARK_NOTIFICATIONS_READ_SUCCESS"
};
