export const USER = {
  SET_AUTHENTICATED: "SET_AUTHENTICATED",
  SET_UNAUTHENTICATED: "SET_UNAUTHENTICATED",
  SIGNUP_START: "SIGNUP_START",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  LOGIN_WITH_EMAIL_AND_PASSWORD_START: "LOGIN_WITH_EMAIL_AND_PASSWORD_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_START: "LOGOUT_START",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOADING_USER: "LOADING_USER",
  CHECK_USER_START: "CHECK_USER_START",
  CHECK_USER_SUCCESS: "CHECK_USER_SUCCESS"
};
